# Generated by Django 5.0.4 on 2024-06-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tag",
            new_name="tags",
        ),
    ]
