# Generated by Django 5.0.4 on 2024-06-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
